INSERT INTO CATEGORIA VALUES(NEWID(), 'Alimentação')
GO

INSERT INTO CATEGORIA VALUES(NEWID(), 'Cartões de Crédito')
GO

INSERT INTO CATEGORIA VALUES(NEWID(), 'Despesas de Casa')
GO

INSERT INTO CATEGORIA VALUES(NEWID(), 'Salário e Renda')
GO

INSERT INTO CATEGORIA VALUES(NEWID(), 'Viagens')
GO

INSERT INTO CATEGORIA VALUES(NEWID(), 'Despesas Médicas')
GO

INSERT INTO CATEGORIA VALUES(NEWID(), 'Outros')
GO

SELECT * FROM CATEGORIA ORDER BY NOME
GO
